SELECT Nombre, Nivel FROM Personajes WHERE Nivel = 10; 
SELECT Nombre FROM Personajes WHERE Nombre LIKE '%or%';
SELECT  Nombre, Región, Poblacion FROM Reinos WHERE Región='Norte' AND Poblacion = 20000;
SELECT * FROM Reinos;
SELECT Nombre, Titulo FROM Personajes Where Titulo='Hechicera' or Titulo='Guerrero';
SELECT Nombre FROM Personajes ORDER BY Nombre ASC;
SELECT * FROM Reinos WHERE Nombre LIKE'%a%';
SELECT COUNT(Tipo) AS 'Total De humanos' FROM Personajes WHERE tipo='humano';
SELECT Región FROM Reinos;
-- SELECT Nombre, Nivel FROM Personajes WHERE Nivel BETWEEN 5 AND 10;
SELECT Nombre, Nivel FROM Personajes WHERE Nivel >= 5 AND Nivel <= 10;
SELECT Nombre, Nivel FROM Personajes WHERE Nivel ORDER BY Nivel DESC LIMIT 3; 
