INSERT INTO Personajes (Nombre, ReinoID) SELECT 'Luna', 4 FROM Reinos WHERE Nombre='Dominio de Lunaris';
DELETE FROM Personajes where Nombre='Luna';
-- INSERT INTO Reinos (Nombre, Región) VALUES ('Valle Esmeralda', 'Oeste');
-- UPDATE Reinos SET Poblacion=60000 WHERE Nombre='Reino de Eldoria';
-- UPDATE Personajes SET Nivel=Nivel+9 WHERE Nombre='Gorim';
-- DELETE FROM Reinos WHERE Nombre='Principado de Solstheim';
-- INSERT INTO Personajes (Nombre, PersonajeID) VALUES ('Bakugou', 6);
-- INSERT INTO artefactosmagicos (Nombre, Poder, DueñoID) VALUES ('Escudo de la Esperanza', 85, 6);
-- UPDATE artefactosmagicos SET DueñoID=7 WHERE Nombre='Espada de Fuego';
-- DELETE FROM Personajes WHERE Nombre='Thorvald';
-- UPDATE Reinos SET Región='Norte' WHERE Nombre='Dominio de Lunaris';
-- UPDATE Participantesbatalla SET BatallaID=3, Rol='Atacante' WHERE PersonajeID=19;
SELECT * FROM Personajes;